a = input('Digite algo: ')
print('O tipo primitivo desse valor é ', type(a))
print('Só tem espaços? ', a.isspace())
print('É um número? ', a.isnumeric())
print('É alfabetico? ', a.isalpha())
print('É alfanumerico? ', a.isalnum())
print('Esta em Maiúsculo? ', a.isupper())
print('Esta em Minúsculo? ', a.islower())
print('Esta capitalizado? ', a.istitle())
